version: "3.8"

services:
  affine:
    build:
      context: ./affine
    ports:
      - "3000:3000"

  chatwoot:
    image: chatwoot/chatwoot
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: production
      SECRET_KEY_BASE: supersecretkey
      FRONTEND_URL: http://localhost:3002
      INSTALLATION_ENV: docker
      POSTGRES_HOST: postgres
      POSTGRES_DATABASE: chatwoot
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]

  postgres:
    build:
      context: ./postgres-with-pgvector
    environment:
      POSTGRES_DB: chatwoot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  backend:
    build: ./backend
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:80"

volumes:
  pgdata:
